### ISSUE TITLE
Mixing the normal CSVs and the bird CSVs breaks chart grouping

### ISSUE THREAD

**Issue by Hex27** [btovis/btovis.github.io#204] opened 2024-02-29 15:58 UTC
Steps to reproduce:

- Upload a normal CSV
- Add a panel
- Upload a bird CSV
The default barchart will lose all its plots

**Comment by CGDogan** [comment] 2024-02-29 18:51
We'll see if this is a duplicate of #199 only after it's resolved

**Closed** 2024-03-01 15:32 UTC
Labels: bug, high-priority, ui, backend
