### ISSUE TITLE
Add data and visualisation to map widget

### ISSUE THREAD

**Issue by George-Ogden** [btovis/btovis.github.io#140] opened 2024-02-27 10:08 UTC

**Comment by George-Ogden** [comment] 2024-02-28 10:54
@Hex27 is this closed by #166 ?

**Comment by Hex27** [comment] 2024-02-28 13:08
No

**Comment by Hex27** [comment] 2024-02-28 13:25
Oh do you mean if the map is done? Not really, I'm not very satisfied with the information that it shows because it's a duplicate of the panel filter right now. I'll still be working on it today

**Comment by Hex27** [comment] 2024-03-01 11:58
Just took another crack at it, but the german data set is extremely homogenous, the species are just distributed very evenly and the points don't change.

Can't see a way to give more info than it currently does.

**Closed by Hex27** 2024-03-01 11:58 UTC
Labels: ui
